name: turbo_air_quotes
description: Turbo Air Quotes (TAQ) - Professional B2B Quote Management System
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_crashlytics: ^5.0.0
  flutter_riverpod: ^2.6.1
  provider: ^6.1.1
  connectivity_plus: ^7.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  fl_chart: ^1.1.1
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^12.0.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  excel: ^4.0.0
  mailer: ^6.0.1
  flutter_dotenv: ^6.0.0
  file_picker: ^10.3.2
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  logger: ^2.0.2+1
  crypto: ^3.0.5
  go_router: ^16.2.4
  cached_network_image: ^3.3.1
  shared_preferences: any
  syncfusion_flutter_pdfviewer: ^31.1.22
  url_launcher: ^6.2.2
  open_file: ^3.3.2
  path: any
  vector_math: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  image: ^4.3.0
flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/logos/turbo_air_logo.png
  - assets/icons/default_product.png
  - assets/thumbnails/
  - assets/screenshots/
