name: turbo_air
description: Turbo Air Equipment Viewer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.0.0
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  
  # Networking
  dio: ^5.3.0
  connectivity_plus: ^5.0.0
  
  # Navigation
  go_router: ^12.0.0
  
  # UI Components
  flutter_adaptive_scaffold: ^0.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # PDF Generation
  pdf: ^3.10.0
  printing: ^5.11.0
  
  # Excel
  excel: ^4.0.0
  
  # File Operations
  file_picker: ^6.0.0
  share_plus: ^7.2.0
  
  # Utilities
  intl: ^0.18.0
  uuid: ^4.0.0
  crypto: ^3.0.0
  collection: ^1.17.0
  json_annotation: ^4.8.1
  
  # Platform specific
  flutter_local_notifications: ^16.0.0
  
  # Icons
  cupertino_icons: ^1.0.6
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/logos/
    - assets/screenshots/